const tenttiNimetDict = {
	"1": "Mikä seuraavista <b>ei ole</b> ohjelmointikieli:",
	"2": "Mikä on maailman yleisin ohjelmointikieli?",
	"3": "Mikä seuraavista EI ole tietotekniikan megatrendi:",
	"4": "Miksi kutsutaan tietokoneen keskusmuistia?",
	"5": "Mistä tulee lyhenne WWW?",
	"6": "Monta opintopistettä AMK-tutkinnon suorittaminen vaatii?",
	"7": "Mikä on 3AMK?",
	"8": "Mitä maksaa 400g makaronipussi?",
	"9": "Miten monta WC-paperirullaa on säästöpakkauksessa?",
	"10": "Miten paljon on 0,33l tölkin pantti?",
    "11": "Mikä näistä on Microsoftin kehittämä pelikonsoli?",
    "12": "Mikä näistä ei kuulu Microsoft Office -pakettiin?",
    "13": "Mikä on Java?",
    "14": "Mikä näistä ei ole suomalainen pelinkehittäjä?",
    "15": "Mikä on Tetris?",
    "16": "Mikä on tradenomi englanniksi?",
    "17": "Kuinka kauan alemman tietojenkäsittelyn korkeakoulututkinnon opiskelu kestää Haaga-Heliassa?",
    "18": "Miten monta WC-paperirullaa on säästöpakkauksessa?",
    "19": "Monesko päivä opintotuki maksetaan? (jos se ei ole viikonloppu)",
    "20": "Mitä maksaa 400g makaronipussi? ",
    "21": "Mikä on Haaga-Helian tikojen ainejärjestö?",
    "22": "Mitä vaaditaan ammattikorkeakouluun pääsemistä varten?",
    "23": "Minä viikonpäivänä opiskelijabileet yleensä ovat? ",
    "24": "Kuka on Haaga-Helian toimitusjohtaja? ",
    "25": "Kuinka monta toimipistettä Haaga-Helialla on",
    "26": "Mitä tutkintoja Haaga-Heliassa voi suorittaa?",
    "27": "Kuinka monta eri koulutusalaa Haaga-heliassa voi opiskella:",
    "28": "Koska Haaga-Helia on perustettu?",
    "29": "Mikä seuraavista ei ole kurssi Haaga-Heliassa?",           
    "30": "Mistä tulee lyhemme 4G?",
    "31": "Mihin käytetään Microsoft Exceliä",
    "32": "Tietojenkäsittelyn koulutusohjelma sisältää mm.",
    "33": "Mikä näistä ei ole tietokoneen käyttöjärjestelmä?",
    "34": "Kuinka monta bittiä on tavu?",
    "35": "Kilotavu on ___ tavua",
    "36": "Ensimmäinen laajalti käytetty käyttöjärjestelmä oli?",
    "37": "Yrityksen sisäistä verkkoa kutsutaan..",
    "38": "Kuinka suuri määrä tietoa on \"nibble\"?",
    "39": "Mikä on vastavalmistuneen Tradenomin aloituspalkka?",
    "40": "Mikä on TRAL?",
    "41": "Missä yrityksissä voi tänä päivänä tehdä ICT-alan töitä?",
    "42": "Mikä näistä ei ole ammattikorkeakoulu?",
    "43": "Mikä seuraavista on henkilöstömäärältään suomen suurin ict-alan yritys:",
    "44": "Kuka seuraavista on tietotekniikka-alan uranuurtaja?",
    "45": "Paljon opiskelija saa tienata/kk jos haluaa nostaa täyden opintotuet?",
    "46": "Minkä tarjoamasta palvelusta tukia voi pyytää?",
    "47": "Mitä näistä eduista opiskelijakortilla voi saada?",
    "48": "Millä näistä kampuksista on Haaga-Helian digitalouden yksikkö?",
    "49": "Miten paljon koululounas maksaa opiskelijakortilla?",
    "50": "Onko ammattikorkeakoulun kursseilla pääsääntöisesti läsnäolopakko, josta ei voi luistaa esimerkiksi töiden takia?",
    "51": "Ammattikorkeakoulussa opiskelu on..",
    "52": "Mikä näistä ei ole tietojenkäsittelyn suuntautumisprofiili?",
    "53": "Mikä on suomen suurin ammattikorkeakoulu?",
    "54": "Edellytetäänkö tietojenkäsittelyn koulutusohjelmassa aiempaa osaamista tietotekniikasta?",
    "55": "Monta korkeakoulua on mukana Haaga-Helian vaihto-opiskeluohjelmassa?",
    "56": "Voiko Haaga-Heliassa suorittaa opintoja myös englanniksi?"
}

const tenttiVaihtoehdotDict = {
	"1": ["Java","Python","Snake"],
	"2": ["Java","SQL","Python"],
	"3": ["Internet of Things","Big data","html-kieli"],
	"4": ["DDR","SSD","RAM"],
	"5": ["World wide web","World with web","Wireless world web"],
	"6": ["170 op","210 op","250 op"],
	"7": ["Kolmen pääkaupunkiseudun ammattikorkeakoulun yhteistyö, johon Haaga-Helia kuuluu","Koodauskieli","korealainen poikabändi"],
	"8": ["Alle 0,50€","Yli 0,50€","Yli 1€"],
	"9": ["Alle 16","Alle 24","Yli 30"],
	"10": ["0,15€","0,20€","0,40€"],
    "11": ["Wii", "Gameboy", "Xbox"],
    "12": ["Word", "Photoshop", "Powerpoint"],
    "13": ["Tietokoneohjelma", "Ohjelmointikieli", "ICT-alan yritys"],
    "14": ["Rovio", "Supercell", "Zynga"],
    "15": ["Legendaarinen peli", "Tietokone-ohjelma", "Ohjelmointikieli"],
    "16": ["Bachelor of Business Administration", "Master of Business Administration", "Business of Bachelor Administration"],
    "17": ["3 vuotta", "3.5 vuotta", "4 vuotta"],
    "18": ["Alle 16", "alle 24", "Yli 30"],
    "19": ["Kuun 1. päivä", "kuun viimeinen päivä","kuun 4. päivä"],
    "20": ["Alle 0,50€", "Yli 0,50€", "Yli 1€"],
    "21": ["Helga", "Atkins", "Hattara"],
    "22": ["Lukio", "Ammattikoulu", "Kumpi vain"],
    "23": ["Maanantai", "Keskiviikko", "Perjantai"],
    "24": ["Karl Fazer", "Teemu Kokko","Mikko Hyppönen"],
    "25": ["1","3","5"],
    "26": ["Ylempiä Ammattikorkeakoulututkintoja","Alempia Ammattikorkeakoulututkintoja", "Molempia"],
    "27": ["15","Lähes 40","Lähes 1000"] ,
    "28": ["2001","1994", "2007"],
    "29": ["Väkevät juomat & Cockatailit", "Oluet ja Pubit", "Toimistovälineiden maailma"],    
    "30": ["4 Gaming", "4th Generation", "4 Genius"],
    "31": ["Muistiinpanojen kirjoittamiseen ", "Taulukkolaskelmiin", "internetsivujen koodaamiseen"],
    "32": ["Ohjelmistokehittämistä", "Ruokatuotantoa", "Matkailun koulutusta"],
    "33": ["IOS", "Linux", "Windows 10"],
    "34": ["8", "2", "64"],
    "35": ["256", "1024", "1000"],
    "36": ["PC-DOS", "OSX", "Windows"],
    "37": ["Sisänetiksi", "Internetiksi", "Intranetiksi"],
    "38": ["2 bittiä", "4 bittiä", "6 bittiä"],
    "39": ["2500-3200€/kk", "1500-2000€/kk", "1000-1500€/kk"],
    "40": ["Trauma-Ala", "Tradenomiliitto", "Trade-lautakunta"],
    "41": ["Elisa", "CGI", "Lähes missä tahansa"],
    "42": ["Laurea", "Metropolia", "Keuda"],
    "43": ["F-secure", "Nokia", "Tieto"],
    "44": ["John Travolta", "Elon Musk", "Dennis Ritchie"],
    "45": ["250€", "570€", "660€"],
    "46": ["Kaupunki", "Kela", "Valtio"],
    "47": ["Alennusta vaatteista", "Alennusta ruoasta", "Molemmista"],
    "48": ["Haagan kampus", "Porvoon kampus", "Pasilan kampus"],
    "49": ["1,65€", "8,70€", "5€"],
    "50": ["Ei", "Kyllä"],
    "51": ["Enimmäkseen käytännönläheisyyteen painottuvaa", "Enimmäkseen teoriapainoitteista"],
    "52": ["ICT-infra", "Digitaaliset palvelut", "Ohjelmistokehittäminen", "ICT-liiketoiminta", "ICT-historia"],
    "53": ["Metropolia", "Haaga-Helia", "TAMK"],
    "54": ["Kyllä", "Ei"],
    "55": ["200", "10", "34"],
    "56": ["Kyllä", "Ei"]
}

const tenttiVastauksetDict = {
	"1": ["Snake"],
	"2": ["SQL"],
	"3": ["html-kieli"],
	"4": ["RAM"],
	"5": ["World wide web"],
	"6": ["210 op"],
	"7": ["Kolmen pääkaupunkiseudun ammattikorkeakoulun yhteistyö, johon Haaga-Helia kuuluu"],
	"8": ["Alle 0,50€"],
	"9": ["Yli 30"],
	"10": ["0,15€"],
    "11": ["Xbox"],
    "12": ["Photoshop"],
    "13": ["Ohjelmointikieli"],
    "14": ["Zynga"],
    "15": ["Legendaarinen peli"],
    "16": ["Bachelor of Business Administration"],
    "17": ["3.5 vuotta"],
    "18": ["Yli 30"],
    "19": ["Kuun 1. päivä"],
    "20": ["Alle 0,50€"],
    "21": ["Atkins"],
    "22": ["Kumpi vain"],
    "23": ["Keskiviikko"],
    "24": ["Teemu Kokko"],
    "25": ["5"],
    "26": ["Molempia"],
    "27": ["Lähes 40"],
    "28": ["2007"],
    "29": ["Toimistovälineiden maailma"],
    "30": ["4th Generation"],
    "31": ["Taulukkolaskelmiin"],
    "32": ["Ohjelmistokehittämistä"],
    "33": ["IOS"],
    "34": ["8"],
    "35": ["1024"],
    "36": ["PC-DOS"],
    "37": ["Intranetiksi"],
    "38": ["4 bittiä"],
    "39": ["2500-3200€/kk"],
    "40": ["Tradenomiliitto"],
    "41": ["Lähes missä tahansa"],
    "42": ["Keuda"],
    "43": ["Nokia"],
    "44": ["Dennis Ritchie"],
    "45": ["660€"],
    "46": ["Kela"],
    "47": ["Molemmista"],
    "48": ["Pasilan kampus"],
    "49": ["1,65€"],
    "50": ["Ei"],
    "51": ["Enimmäkseen käytännönläheisyyteen painottuvaa"],
    "52": ["ICT-historia"],
    "53": ["Metropolia"],
    "54": ["Ei"],
    "55": ["200"],
    "56": ["Kyllä"]
}

const tenttiResponseDict = {
	"1": ["Python ja Java ovat ohjelmointikieliä, Snake sen sijaan ei."],
	"2": ["Koodauskielien suosiosta ollaan yleisesti montaa mieltä, mutta yleisesti Javaa pidetään suosituimpana ohjelmointikielenä."],
	"3": ["Internet of Things sekä Big Data ovat tulevaisuuden trendejä. Esimeriksi Big Datan uskotaan kymmenkertaistuvan vuoteen 2025 mennessä."],
	"4": ["RAM eri Random Access Memory viittaa tietokoneen keskusmuistiin. SSD on tietokoneen massamuisti, DDR sen sijaan keskusmuistin tyyppi."],
	"5": ["Oikea vastaus on World Wide Web."],
	"6": ["Tradenomin tutkinnon suorittaminen vaatii 210 opintopistettä."],
	"7": ["3AMK on kolmen koulun liittouma, johon kuuluu Laurea, Metropolia sekä Haaga-Helia. Opiskelija voi halutessaan hyödyntää näiden koulujen kurssitarjontoja."],
	"8": ["400g makaronipussi maksaa keskimäärin 0,20€-0,30€"],
	"9": ["Säästöpakkaukseen kuuluu merkistä riippuen 32-40 kpl WC-paperirullaa."],
	"10": ["0,33l tölkin pantti on 0,15€."],
    "11": ["Xbox on Microsoftin kehittämä pelikonsoli"],
    "12": ["Photoshop ei kuulu Microsoft-office pakettiin."],
    "13": ["Java on ohjelmointikieli sekä yleisen uskomuksen mukaan maailman suosituin lajissaan."],
    "14": ["Zynga on selainpelejä julkaiseva <b>yhdysvaltalainen</b> ohjelmistoyritys."],
    "15": ["Tetris on tietokonepeli, jonka on alun perin tehnyt neuvostoliittolainen Aleksei Pažitnov kesäkuussa 1984."],
    "16": ["Tradenomi on englanniksi Bachelor of Business Administration."],
    "17": ["Arvioitu valmistumisaika on yleisesti 3.5 vuotta."],
    "18": ["Säästöpakkaukseen kuuluu merkistä riippuen 32-40 kpl WC-paperirullaa."],
    "19": ["Opintotuki maksetaan yleisesti joka kuun 1. päivä, riippuen osuuko viikonloppu maksupäivän kohdalle vai ei."],
    "20": ["400g makaronipussi maksaa keskimäärin 0,20€-0,30€"],
    "21": ["Atkins on Haaga-Helian aineyhdistys. Helga taasen on Haaga-Helian opiskelijakunta. Hattara ei ole yhtään mitään."],
    "22": ["Ammattikorkeakouluun voi hakea kummallakin toisen asteen suoritetulla koulutuksella."],
    "23": ["Opiskelijatapahtumat järjestetään yleisesti keskiviikkoisin."],
    "24": ["Haaga-Helian toimitusjohtaja on Teemu Kokko."],
    "25": ["Haaga-Helialla on yhteensä viisi toimipistettä: Vierumäellä, Porvoossa sekä Helsingissä kolme: Malmilla, Haagassa sekä Pasilassa."],
    "26": ["Haaga-Heliassa voi suorittaa sekä ylempiä että alempia korkeakoulututkintoja."],
    "27": ["Haaga-Heliassa on lähes 40 ammattitutkintoon johtavaa koulutusohjelmaa, joista osa on ruotsiksi ja englanniksi."],
    "28": ["Haaga-Helia aloitti toimintansa 2007, kun Helsingin liiketalouden ammattikorkeakoulu Helia sekä Haaga Instituutin ammattikorkeakoulu yhdistyi."],
    "29": ["Kuten kysymyksestä voi huomata, Haaga-Heliassa on laaja kurssitarjonta myös tietotekniikan ulkopuolelta. Toimistovälineiden maailma ei kuitenkaan siihen kuulu."],
    "30": ["4G viittaa termiin 4th Generation (neljäs sukupolvi)."],
    "31": ["Excel on taulukkolaskennassa käytetty työkalu."],
    "32": ["Ohjelmistotuotannon valinneet tietojenkäsittelyn opiskelijat opiskelevat pääsääntöisesti ohjelmistokehittämistä."],
    "33": ["IOS on Applen kehittämä mobiililaitteiden käyttöjärjestelmä."],
    "34": ["Yksi tavu (\"byte\") on 8-bittiä."],
    "35": ["Yksi kilotavu (engl. kb) on 1024 tavua."],
    "36": ["Oikea vastaus on PC-DOS"],
    "37": ["Tavallisesti <b>intranetillä</b> tarkoitetaan organisaation lähiverkkoa, jota käytetään yrityksen tai yhteisön sisäiseen viestintään ja tietojenkäsittelytoimiin"],
    "38": ["Nibble, joka tunnetaan myös puolibittinä, on 4 bittiä."],
    "39": ["Tradenomi tienaa keskimäärin 2500-3200€/kk."],
    "40": ["TRAL on tradenomiliitto."],
    "41": ["ICT-alan töitä ovi nykyään tehdä lähes missä tahansa yrityksessä."],
    "42": ["Keuda ei ole ammattikorkeakoulu."],
    "43": ["Nokia on henkilöstömäärältä mitattuna suomen suurin yritys (v. 2017)."],
    "44": ["Dennis Ritchie oli yhdysvaltalainen tietojenkäsittelijä, joka tunnettiin erityisesti C-ohjelmointikielen sekä UNIX-käyttöjärjestelmän kehittäjänä."],
    "45": ["Opiskelijalla voi olla kuukaudessa omia tuloja 660€, joskin tähän vaikuttaa monet muut tekijät."],
    "46": ["Opiskelijalle suunnatut tuet myöntää ja maksaa Kela."],
    "47": ["Opiskelijakortilla voi saada alennusta useista eri paikoista."],
    "48": ["Haaga-Helian digitalouden yksikkö sijaitsee Pasilan kampuksella."],
    "49": ["Koululounas maksaa Kelan myöntämällä ruokakortilla 1,65€ (v.2018)"],
    "50": ["Oppitunneilla ei ole pääsääntöisesti läsnäolopakkoa, joten päivätoteutuksessakin opiskelu on hyvin joustavaa oppilaan kannalta."],
    "51": ["Tietojenkäsittelyn koulutusohjelman opiskelu on hyvin käytännönläheistä sekä käytännönläheisempää kuin esimerkiksi tietotekniikan alan opiskelu tiedekorkeakouluissa."],
    "52": ["ICT-historia ei ole suoranaisesti tietojenkäsittelyn koulutusohjelman suuntautumisprofiili."],
    "53": ["Haaga-Helian yhteistyökoulu <b>Metropolia</b> on suomen suurin ammattikorkeakoulu."],
    "54": ["Tietojenkäsitelyn koulutusohjelmaan ei edellytetä aikasempaa kokemusta tai osaamista."],
    "55": ["Haaga-Helian vaihto-opiskeluohjelmaan kuuluu tällä hetkellä 200 koulua monessa eri maanosasassa."],
    "56": ["Haaga-Heliassa on kursseja myös englanniksi sekä ruotsiksi."]
}

const tenttiKysymykset = []

for (key in tenttiNimetDict) {
    tenttiKysymykset.push(key)
}